import * as THREE from 'three'
import '@fontsource/pixelify-sans/500.css'
import '@fontsource/pixelify-sans/700.css'
import '@fontsource/dotgothic16'

// Pixelify's 2 and 5 read oddly — 'Studdy Digits' (public/studdy-digits.otf,
// generated by scripts/gen-digits.mjs) redraws JUST those two glyphs on
// Pixelify's exact advance and cap height, so nothing jitters or resizes.
const digitFix = new FontFace('Studdy Digits', `url(${import.meta.env.BASE_URL}studdy-digits.otf)`, {
  unicodeRange: 'U+0032, U+0035',
  weight: '100 900',
})
document.fonts.add(digitFix)
digitFix.load().catch(() => {})
import './styles.css'
import { installPixelUI, installCursor } from './pixelui'
import { buildWorld } from './world'
import { Lighting } from './lighting'
import { buildUI, heartBurst } from './ui'
import { createGame, type Game } from './game'
import { buildEditor, type Editor } from './editor'
import { unlock, sfx } from './sounds'
import * as store from './store'
import { CATALOG } from './items'
import { needsOnboarding, runOnboarding } from './onboarding'
import { initCloud, getSupabase, cloudUser } from './cloud'
import { initPresence, setPlace, updateState } from './presence'
import { initSocial, fetchCafeByUser, fetchCafeByHandle, requestFriend } from './social'
import { toast } from './ui'
import { openGallery, openDrawPad, seedNotes, closeGuestbook } from './guestbook'
import { openSalon, closeSalon } from './salon'
import { closeProfileCard } from './ui'
import { buildChat } from './chat'
import { runTour } from './tour'

installPixelUI()
installCursor()

const params = new URLSearchParams(location.search)
const isShowcase = params.has('showcase')

const stage = document.getElementById('stage')!

const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true })
// light supersampling on top of the device ratio smooths remaining voxel edges
renderer.setPixelRatio(Math.min(window.devicePixelRatio * 1.5, 3))
renderer.shadowMap.enabled = true
renderer.shadowMap.type = THREE.PCFSoftShadowMap
renderer.outputColorSpace = THREE.SRGBColorSpace
renderer.toneMapping = THREE.NoToneMapping
stage.appendChild(renderer.domElement)

const scene = new THREE.Scene()

// ---------- fixed isometric diorama camera ----------
const TARGET = new THREE.Vector3(13.5, 3.2, 9.5)
const AZIMUTH = Math.PI / 4
const ELEVATION = 0.56 // ~32°
let NEED_W = 21
let NEED_H = 14.5
const camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 1, 300)
function placeCamera() {
  const d = 90
  camera.position.set(
    TARGET.x + Math.cos(ELEVATION) * Math.sin(AZIMUTH) * d,
    TARGET.y + Math.sin(ELEVATION) * d,
    TARGET.z + Math.cos(ELEVATION) * Math.cos(AZIMUTH) * d
  )
  camera.lookAt(TARGET)
}
let zoomF = 1 // 1 = whole café; user can zoom 1..5
function fitFrustum() {
  const aspect = window.innerWidth / window.innerHeight
  let halfH = NEED_H
  if (NEED_W / aspect > NEED_H) halfH = NEED_W / aspect
  halfH /= zoomF
  camera.left = -halfH * aspect
  camera.right = halfH * aspect
  camera.top = halfH
  camera.bottom = -halfH
  camera.updateProjectionMatrix()
}
let extentW = 28
let extentD = 20
function setExtent(w: number, d: number) {
  extentW = w
  extentD = d
  TARGET.set(w / 2, 2.9, d / 2 + 0.5)
  NEED_W = Math.max(12, (w + d) * 0.4375 + 0.6)
  NEED_H = Math.max(9, (w + d) * 0.302 + 0.5)
  placeCamera()
  fitFrustum()
}
placeCamera()
fitFrustum()

function resize() {
  renderer.setSize(window.innerWidth, window.innerHeight)
  fitFrustum()
}
window.addEventListener('resize', resize)
resize()

// ---------- zoom (wheel / pinch) + drag-pan; angle stays fixed ----------
const camRight = new THREE.Vector3()
const camUp = new THREE.Vector3()
function clampTarget() {
  TARGET.x = Math.min(extentW - 1, Math.max(1, TARGET.x))
  TARGET.z = Math.min(extentD - 1, Math.max(1, TARGET.z))
}
function setZoom(next: number, anchorX?: number, anchorY?: number) {
  const prev = zoomF
  zoomF = Math.min(5, Math.max(1, next))
  if (zoomF === prev) return
  if (anchorX !== undefined && anchorY !== undefined) {
    const ndcX = (anchorX / window.innerWidth) * 2 - 1
    const ndcY = -(anchorY / window.innerHeight) * 2 + 1
    const halfWPrev = (camera.right - camera.left) / 2
    const halfHPrev = (camera.top - camera.bottom) / 2
    camera.updateMatrixWorld()
    camRight.setFromMatrixColumn(camera.matrixWorld, 0)
    camUp.setFromMatrixColumn(camera.matrixWorld, 1)
    const shrink = 1 - prev / zoomF
    TARGET.addScaledVector(camRight, ndcX * halfWPrev * shrink)
    TARGET.addScaledVector(camUp, ndcY * halfHPrev * shrink)
    clampTarget()
  }
  placeCamera()
  fitFrustum()
}
renderer.domElement.addEventListener('wheel', (e) => {
  e.preventDefault()
  setZoom(zoomF * Math.exp(-e.deltaY * 0.0016), e.clientX, e.clientY)
}, { passive: false })

const pointers = new Map<number, { x: number; y: number }>()
let dragDist = 0
let pinchDist = 0
let charDrag = false // carrying the avatar: suppress camera panning
renderer.domElement.addEventListener('pointerdown', (e) => {
  if (game) {
    setRayFromEvent(e)
    if (game.startDrag(raycaster)) {
      charDrag = true
      return // the pointer is holding the character, not the camera
    }
  }
  pointers.set(e.pointerId, { x: e.clientX, y: e.clientY })
  dragDist = 0
  if (pointers.size === 2) {
    const [a, b] = [...pointers.values()]
    pinchDist = Math.hypot(a.x - b.x, a.y - b.y)
  }
})
window.addEventListener('pointermove', (e) => {
  if (charDrag && game) {
    setRayFromEvent(e)
    game.dragMove(raycaster)
    return
  }
  // ghost placement + seat hover follow the pointer
  if (game && pointers.size === 0) {
    setRayFromEvent(e)
    game.pointerMove(raycaster)
  }
  const p = pointers.get(e.pointerId)
  if (!p) return
  if (pointers.size === 1) {
    const dx = e.clientX - p.x
    const dy = e.clientY - p.y
    dragDist += Math.abs(dx) + Math.abs(dy)
    const wpp = (camera.right - camera.left) / window.innerWidth
    camera.updateMatrixWorld()
    camRight.setFromMatrixColumn(camera.matrixWorld, 0)
    camUp.setFromMatrixColumn(camera.matrixWorld, 1)
    TARGET.addScaledVector(camRight, -dx * wpp)
    TARGET.addScaledVector(camUp, dy * wpp)
    clampTarget()
    placeCamera()
  } else if (pointers.size === 2) {
    p.x = e.clientX
    p.y = e.clientY
    const [a, b] = [...pointers.values()]
    const d = Math.hypot(a.x - b.x, a.y - b.y)
    if (pinchDist > 0) setZoom(zoomF * (d / pinchDist), (a.x + b.x) / 2, (a.y + b.y) / 2)
    pinchDist = d
    return
  }
  p.x = e.clientX
  p.y = e.clientY
})
window.addEventListener('pointerup', (e) => {
  if (charDrag && game) {
    // released off-canvas: still set the character down
    charDrag = false
    game.endDrag()
  }
  pointers.delete(e.pointerId)
})
window.addEventListener('pointercancel', (e) => pointers.delete(e.pointerId))
renderer.domElement.addEventListener('dblclick', () => {
  setExtent(extentW, extentD)
  zoomF = 1
  fitFrustum()
})

// ---------- worlds: game (default) or the style showcase (?showcase) ----------
let editor: Editor | null = null
let lighting: Lighting
let game: Game | null = null
let showcase: ReturnType<typeof buildWorld> | null = null

if (isShowcase) {
  showcase = buildWorld()
  scene.add(showcase.group)
  setExtent(28, 20)
  lighting = new Lighting(scene, showcase)
} else {
  game = createGame(scene, {
    onRoomExtent: (w, d) => setExtent(w, d),
    onPendants: (p) => lighting?.setPendantGrid(p),
    onSelection: (sel) => editor?.setSelection(sel),
    onCapacity: (n) => editor?.setCapacity(n),
    onPlacingChange: (id) => editor?.setPlacing(id),
    onLampsChanged: () => lighting?.refresh(),
    onVisit: (cafe) => {
      // traveling closes whatever you had open
      closeGuestbook()
      closeSalon()
      closeProfileCard()
      editor?.setVisiting(cafe)
      setPlace(cafe?.id ?? null) // my presence follows me
    },
    onSession: (s) => {
      editor?.setSession(s)
      updateState(
        s
          ? { seatKey: s.seatKey, napkin: s.napkin, headphones: s.headphones, since: s.startedAt }
          : { seatKey: null, napkin: '' }
      )
    },
    onPatronCard: (data, x, y) => ui.openProfileCard(x, y, data),
    onGuestbook: (atHome) => {
      const uiEl = document.getElementById('ui')!
      if (atHome) openGallery(uiEl)
      else {
        const v = game?.getVisiting()
        // at a real user's café the note truly lands in their book
        const ownerId = v?.id.startsWith('user:') ? v.id.slice(5) : undefined
        openDrawPad(uiEl, v?.name ?? 'this café', false, ownerId)
      }
    },
    onDoor: (atHome) => {
      if (atHome) editor?.openDirectory() // stepping out? pick a place
      else game?.visit(null) // the door always leads home
    },
    onSalon: (kind) => openSalon(document.getElementById('ui')!, kind),
    onFloat: (text, kind) => {
      // damage-indicator style: pixel text rising from the player's head
      const anchor = game?.getPlayerAnchor()
      let x = window.innerWidth / 2
      let y = window.innerHeight / 2
      if (anchor) {
        const v = anchor.project(camera)
        x = (v.x * 0.5 + 0.5) * window.innerWidth
        y = (-v.y * 0.5 + 0.5) * window.innerHeight
      }
      const el = document.createElement('span')
      el.className = `px-float ${kind}`
      el.textContent = text
      el.style.left = `${x}px`
      el.style.top = `${y}px`
      document.body.appendChild(el)
      setTimeout(() => el.remove(), 1400)
    },
  })
  lighting = new Lighting(scene, game.handle)
  lighting.setPendantGrid(game.handle.pendantPositions)
}

// ---------- UI ----------
const ui = buildUI({
  onMode: (m) => lighting.setMode(m),
  onRoomLight: (v) => lighting.setRoomLight(v),
  onFurnitureLight: (v) => lighting.setFurnitureLight(v),
  onTurn: () => game?.turnPlayer(),
  onFriendUser: async (userId) => toast(await requestFriend(userId)),
  onVisitUser: async (userId) => {
    if (userId === cloudUser()?.id) {
      game?.visit(null) // that's you — just head home
      return
    }
    const cafe = await fetchCafeByUser(userId)
    if (cafe && game) game.visit(cafe)
    else toast('their café is closed right now ♪')
  },
})
lighting.onBackground = (a, b) => ui.setBackground(a, b)
if (game) {
  editor = buildEditor(document.getElementById('ui')!, game)
  editor.setCapacity(game.capacity())
}

// ---------- speech bubbles (chat lines float over heads, then fade) ----------
function showBubble(anchor: () => THREE.Vector3 | null, text: string, ms = 4500) {
  const el = document.createElement('div')
  el.className = 'chat-bubble'
  el.textContent = text
  document.body.appendChild(el)
  const place = () => {
    const a = anchor()
    if (!a) {
      el.style.display = 'none'
      return
    }
    el.style.display = ''
    const v = a.project(camera)
    el.style.left = `${(v.x * 0.5 + 0.5) * window.innerWidth}px`
    el.style.top = `${(-v.y * 0.5 + 0.5) * window.innerHeight}px`
  }
  place()
  const iv = setInterval(place, 120)
  setTimeout(() => {
    clearInterval(iv)
    el.classList.add('gone')
    setTimeout(() => el.remove(), 300)
  }, ms)
}

const chat = game ? buildChat(document.getElementById('ui')!, game, showBubble) : null

// accounts + cloud saves (no-op unless Supabase env vars are set)
if (game) {
  initCloud()
  // realtime presence: real people in the room, live chat, directory counts
  initPresence({
    onPatrons: (patrons) => game!.setRemotePatrons(patrons),
    onChat: (from, text) => {
      chat?.addLine(from, text)
      showBubble(() => game!.getSimAnchor(from), text)
    },
    onLobby: (counts) => editor?.setLiveCounts(counts),
  })
  // napkin edits and headphone flips ride along every few seconds
  setInterval(() => {
    const s = game!.getSession()
    if (s) updateState({ napkin: s.napkin, headphones: s.headphones })
  }, 6000)
  // a new look or name shows up for everyone right away
  store.on('avatar', () => updateState({}))
  store.on('info', () => updateState({}))
  // the social loop: publish my café, watch for friend requests
  initSocial({ onRequestCount: (n) => editor?.setRequestCount(n) })
}

// ---------- sound unlock + UI ticks ----------
document.addEventListener('pointerdown', (e) => {
  unlock() // autoplay policy: first gesture wakes the AudioContext
  if ((e.target as HTMLElement).closest?.('.glossy-btn')) sfx.tick()
})

// ---------- splash ----------
if (!isShowcase) {
  const splash = document.createElement('div')
  splash.className = 'splash'
  splash.innerHTML = `
    <img class="splash-logo" alt="Studdy" />
    <div class="splash-tag">a study spot that never closes ♪</div>
    <div class="splash-enter">— click to open the café —</div>
  `
  document.body.appendChild(splash)
  import('./pixelui').then(({ makeLogo }) =>
    makeLogo('Studdy').then(({ url, w }) => {
      const img = splash.querySelector('.splash-logo') as HTMLImageElement
      img.src = url
      img.style.width = `${w * 5}px`
    })
  )
  // no sprint clock until the café has actually opened (post-onboarding)
  if (needsOnboarding()) document.querySelector('.clock-pill')?.classList.add('hidden')

  splash.addEventListener(
    'pointerdown',
    () => {
      unlock()
      sfx.pop()
      // an unhurried arrival: hold on "opening…" for a beat, then fade in
      const enter = splash.querySelector('.splash-enter') as HTMLElement
      enter.textContent = 'opening the café ♪'
      enter.style.animation = 'none'
      setTimeout(() => {
        splash.classList.add('gone')
        setTimeout(() => splash.remove(), 900)
        // a shared "come study at my café" link: walk over once signed in
        const linkHandle = new URLSearchParams(location.search).get('cafe')
        const followCafeLink = async () => {
          if (!game || !linkHandle) return
          for (let i = 0; i < 12; i++) {
            const cafe = await fetchCafeByHandle(linkHandle)
            if (cafe) {
              if (cafe.id === `user:${cloudUser()?.id}`) {
                toast('this is your own café link ♪')
                return
              }
              game.visit(cafe)
              toast(`welcome to ${cafe.name} ♪`)
              return
            }
            if (getSupabase()) break // signed in and it's really not there
            await new Promise((r) => setTimeout(r, 1500)) // still connecting
          }
          toast('that café isn’t open right now ♪')
        }
        // first run: the setup wizard takes it from here
        if (game && needsOnboarding()) {
          hintsPaused = true
          runOnboarding(document.getElementById('ui')!, game, () => {
            hintsPaused = false
            // the café is open: the communal clock starts mattering now
            document.querySelector('.clock-pill')?.classList.remove('hidden')
            if (store.save.info.guestbook) seedNotes()
            runTour(document.getElementById('ui')!, () => followCafeLink())
          })
        } else {
          followCafeLink()
        }
      }, 850)
    },
    { once: true }
  )
}

// ---------- onboarding hints (first run) ----------
let hintsPaused = false
if (game) {
  const hintEl = document.querySelector('.hint') as HTMLElement
  const HINT_KEY = 'studdy-hint-stage'
  let stage = Number(localStorage.getItem(HINT_KEY) ?? 0)
  const bump = (s: number) => {
    if (s > stage) {
      stage = s
      localStorage.setItem(HINT_KEY, String(stage))
    }
  }
  const HINTS = [
    'your order is on its way — watch the door ♪',
    'tap ✎ edit café and place your furniture',
    'click any free seat to start studying ♪',
    'you earn 1 ◍ per focused minute · ✈ visit friends too',
    'drag to look around · scroll to zoom · ✎ edit your café ♪',
  ]
  const tickHints = () => {
    if (!game || hintsPaused) return
    const hasFurniture = Object.entries(store.save.inventory).some(([k, n]) => n > 0 && CATALOG[k]?.placement === 'floor')
    const hasSeat = store.save.placed.some((p) => CATALOG[p.itemId]?.seats)
    if (stage === 0 && hasFurniture) bump(1)
    if (stage <= 1 && hasSeat) bump(2)
    if (stage <= 2 && game.getSession()) bump(3)
    if (stage <= 3 && game.getVisiting()) bump(4)
    hintEl.textContent = HINTS[Math.min(stage, HINTS.length - 1)]
  }
  tickHints()
  setInterval(tickHints, 1200)
}

// ---------- picking ----------
const raycaster = new THREE.Raycaster()
const pointer = new THREE.Vector2()
function setRayFromEvent(e: { clientX: number; clientY: number }) {
  pointer.set((e.clientX / window.innerWidth) * 2 - 1, -(e.clientY / window.innerHeight) * 2 + 1)
  raycaster.setFromCamera(pointer, camera)
}
renderer.domElement.addEventListener('pointerup', (e) => {
  if (charDrag && game) {
    charDrag = false
    setRayFromEvent(e)
    if (!game.endDrag()) game.sceneClick(raycaster, e.clientX, e.clientY) // it was a tap: open the card
    return
  }
  if (dragDist > 6 || pointers.size > 1) return // it was a drag or pinch, not a click
  setRayFromEvent(e)
  if (game) {
    game.sceneClick(raycaster, e.clientX, e.clientY)
    return
  }
  if (showcase) {
    const avatarHit = raycaster.intersectObjects(showcase.avatarMeshes, true)
    if (avatarHit.length) {
      ui.openProfileCard(e.clientX, e.clientY)
      return
    }
    const catHit = raycaster.intersectObjects(showcase.catMeshes, true)
    if (catHit.length) heartBurst(e.clientX, e.clientY)
  }
})
window.addEventListener('keydown', (e) => {
  if (!game) return
  if ((e.target as HTMLElement)?.tagName === 'INPUT' || (e.target as HTMLElement)?.tagName === 'TEXTAREA') return
  if (e.key === 'r' || e.key === 'R') {
    if (game.isPlacing()) game.rotateGhost()
    else game.turnPlayer() // face a new direction while standing
  }
  if (e.key === 'Escape') game.cancelPlacing()
})

// ---------- retro outline pass ----------
const OUTLINE_LAYER = 1
const sceneRT = new THREE.WebGLRenderTarget(1, 1, { samples: 4, depthBuffer: true })
const maskRT = new THREE.WebGLRenderTarget(1, 1, {
  type: THREE.HalfFloatType,
  format: THREE.RGBAFormat,
  depthBuffer: true,
})
const maskMat = new THREE.ShaderMaterial({
  vertexShader: 'void main(){ gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }',
  fragmentShader: 'void main(){ gl_FragColor = vec4(gl_FragCoord.z, 0.0, 0.0, 1.0); }',
})
const compMat = new THREE.ShaderMaterial({
  depthTest: false,
  depthWrite: false,
  blending: THREE.NoBlending,
  uniforms: {
    tScene: { value: sceneRT.texture },
    tMask: { value: maskRT.texture },
    uTexel: { value: new THREE.Vector2() },
    uRadius: { value: 2.2 },
    uThresh: { value: 0.0012 },
    uCEdge: { value: 0.16 },
    uDark: { value: 0.72 },
    uSat: { value: 1.35 },
  },
  vertexShader: 'varying vec2 vUv; void main(){ vUv = position.xy * 0.5 + 0.5; gl_Position = vec4(position.xy, 0.0, 1.0); }',
  fragmentShader: `
    uniform sampler2D tScene, tMask;
    uniform vec2 uTexel;
    uniform float uRadius, uThresh, uCEdge, uDark, uSat;
    varying vec2 vUv;
    vec3 oetf(vec3 c) {
      return mix(12.92 * c, 1.055 * pow(c, vec3(1.0 / 2.4)) - 0.055, step(vec3(0.0031308), c));
    }
    void main() {
      vec4 scene = texture2D(tScene, vUv);
      float dc = texture2D(tMask, vUv).r;
      bool oc = dc < 0.9999;
      bool hit = false;
      float bestD = oc ? dc : 1.0;
      vec2 bestUv = vUv;
      for (int i = 0; i < 4; i++) {
        vec2 off = i == 0 ? vec2(uTexel.x, 0.0) : i == 1 ? vec2(-uTexel.x, 0.0)
                 : i == 2 ? vec2(0.0, uTexel.y) : vec2(0.0, -uTexel.y);
        vec2 uvn = vUv + off * uRadius;
        float dn = texture2D(tMask, uvn).r;
        bool on = dn < 0.9999;
        if (oc != on) hit = true;
        else if (oc && on && abs(dc - dn) > uThresh) hit = true;
        else if (oc && on) {
          vec3 cn = texture2D(tScene, uvn).rgb;
          vec3 dcol = abs(scene.rgb - cn);
          if (dcol.r + dcol.g + dcol.b > uCEdge) hit = true;
        }
        if (on && dn < bestD) { bestD = dn; bestUv = uvn; }
      }
      if (!hit) {
        gl_FragColor = vec4(oetf(scene.rgb), scene.a);
        return;
      }
      vec3 base = texture2D(tScene, bestUv).rgb;
      float l = dot(base, vec3(0.299, 0.587, 0.114));
      vec3 ink = clamp(mix(vec3(l), base, uSat) * uDark, 0.0, 1.0);
      gl_FragColor = vec4(oetf(ink), 1.0);
    }`,
})
const compScene = new THREE.Scene()
compScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2, 2), compMat))
const compCam = new THREE.Camera()
const clearColorTmp = new THREE.Color()
function renderFrame() {
  const size = renderer.getDrawingBufferSize(new THREE.Vector2())
  if (maskRT.width !== size.x || maskRT.height !== size.y) {
    maskRT.setSize(size.x, size.y)
    sceneRT.setSize(size.x, size.y)
  }
  compMat.uniforms.uTexel.value.set(1 / size.x, 1 / size.y)

  renderer.setRenderTarget(sceneRT)
  renderer.render(scene, camera)

  renderer.getClearColor(clearColorTmp)
  const prevAlpha = renderer.getClearAlpha()
  camera.layers.set(OUTLINE_LAYER)
  scene.overrideMaterial = maskMat
  renderer.setRenderTarget(maskRT)
  renderer.setClearColor('#ffffff', 1)
  renderer.clear()
  renderer.render(scene, camera)
  scene.overrideMaterial = null
  camera.layers.set(0)
  renderer.setClearColor(clearColorTmp, prevAlpha)

  renderer.setRenderTarget(null)
  renderer.render(compScene, compCam)
}

// the floating action label over whatever you're hovering
const hoverLabelEl = document.createElement('div')
hoverLabelEl.className = 'hover-label'
hoverLabelEl.style.display = 'none'
document.body.appendChild(hoverLabelEl)
const hoverV = new THREE.Vector3()

const clockT = new THREE.Clock()
let lastFrame = 0
function step(dt: number) {
  if (showcase) showcase.update(dt, clockT.elapsedTime)
  if (game) game.handle.update(dt, clockT.elapsedTime)
  const hi = game?.getHoverInfo()
  if (hi) {
    const t = clockT.elapsedTime
    hoverLabelEl.style.display = ''
    hoverLabelEl.textContent = hi.text
    hoverV.set(hi.x, hi.y, hi.z).project(camera)
    hoverLabelEl.style.left = `${(hoverV.x * 0.5 + 0.5) * window.innerWidth}px`
    hoverLabelEl.style.top = `${(-hoverV.y * 0.5 + 0.5) * window.innerHeight - Math.sin(t * 2) * 5}px`
    hoverLabelEl.style.opacity = String(0.65 + 0.35 * Math.sin(t * 2.4)) // blinks with the outline
  } else {
    hoverLabelEl.style.display = 'none'
  }
  lighting.update(dt)
  renderFrame()
}
function frame() {
  lastFrame = performance.now()
  step(Math.min(clockT.getDelta(), 0.05))
  requestAnimationFrame(frame)
}
frame()
// keep transitions moving if rAF is throttled (hidden/embedded tab)
setInterval(() => {
  if (performance.now() - lastFrame > 400) {
    clockT.getDelta()
    step(0.35)
  }
}, 400)

;(window as any).__studdy = {
  lighting,
  game,
  showcase,
  scene,
  step,
  camera,
  zoom(f: number, cx = TARGET.x, cy = 3.2, cz = TARGET.z) {
    TARGET.set(cx, cy, cz)
    placeCamera()
    const a = window.innerWidth / window.innerHeight
    const h = NEED_H / f
    camera.left = -h * a
    camera.right = h * a
    camera.top = h
    camera.bottom = -h
    camera.updateProjectionMatrix()
  },
}
